name: Run tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: astral-sh/setup-uv@v5
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make install
    
    - name: Check linter
      run: make lint

    - name: Run tests
      run: make test
